name: CI

on: [push, pull_request]

jobs:
  testsuite:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        TYPO3: ['11' , '12', '13']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install composer dependencies TYPO3 13
        if: matrix.TYPO3 == '13'
        run: |
          composer install --no-progress --no-interaction

      - name: Install composer dependencies TYPO3 12
        if: matrix.TYPO3 == '12'
        run: |
          composer require typo3/cms-core:^12.4 --no-progress --no-interaction --dev -W
      - name: Install composer dependencies TYPO3 11
        if: matrix.TYPO3 == '11'
        run: |
          composer require typo3/cms-core:^11.5 --no-progress --no-interaction --dev -W
      - name: Phpstan
        run: ./vendor/bin/phpstan analyze -c phpstan.neon
      - name: Phpcsfix
        run: ./vendor/bin/php-cs-fixer fix --config=php-cs-fixer.php --dry-run --stop-on-violation --using-cache=no
